#!/usr/bin/env bash
# transfers a file from our client to a server

# checking if the no of parameters is < 3
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# transfer file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username"@"$server_ip":~/
