#!/usr/bin/env bash
# installing nginx

# updating and installing
sudo apt-get -y update
sudo apt-get -y install nginx

# adding firewall
sudo ufw allow 'Nginx HTTP'

# Creating an index.html page with a string
echo "Hello World!" | sudo tee /var/www/html/index.html

# Checking configurations for Syntax errors
sudo nginx -t

# Restarting nginx service
sudo service nginx restart
