#!/usr/bin/env bash
# Install and setup nginx into the server

sudo apt-get -y update
sudo apt-get -y install nginx

# allowing nginx on firewall
sudo ufw allow "Nginx HTTP"
# create a html page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# restart nginx
sudo service nginx restart
