#!/usr/bin/env bash
# installing nginx web server

# updating and upgrading apt-get
sudo apt-get update -y && apt-get upgrade -y

# installing nginx
sudo apt-get install nginx -y

# starting nginx service
sudo service nginx start

# adding string to a page
echo "Hello World!" | sudo tee /var/www/html/index.html

# restarting nginx service
sudo service nginx restart
