#!/usr/bin/env bash
# redirecting to another page

new_string="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo sed -i "19i $new_string" /etc/nginx/sites-available/default

sudo service nginx start
