#!/usr/bin/env bash
# redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx

sudo service nginx start

new_string="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "19i $new_string" /etc/nginx/sites-available/default

# restart nginx
sudo service nginx restart

sudo service nginx reload
