#!/usr/bin/env bash
# Managing nginx installation, redirection and 404 error

sudo apt-get -y update
sudo apt-get install -y nginx
sudo systemctl start nginx

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo systemctl reload nginx

if ! grep -q "location /redirect_me {" /etc/nginx/sites-enabled/default; then
sudo sed -i '/server_name _;/a\
        location \/redirect_me {\
            return 301 https:\/\/google.com;\
        }' /etc/nginx/sites-enabled/default
sudo systemctl reload nginx
fi

if ! grep -q "error_page 404 /404.html;" /etc/nginx/sites-enabled/default; then
# Configuring Custom 404 page
sudo sed -i '/server_name _;/a\
        error_page 404 /404.html;' /etc/nginx/sites-enabled/default

# Reloading Nginx service
sudo systemctl reload nginx
fi
